version: "3.8"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mahyargh
      MONGO_INITDB_ROOT_PASSWORD: mahyargh
    volumes:
      - ./data:/data/db
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    networks:
      - fullstack

  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_HOST: mongodb
      DB_USER: mahyargh
      DB_PASSWORD: mahyargh
      DB_NAME: comp3123_assignment2
      DB_PORT: 27017
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend/uploads:/usr/src/app/uploads
      - logs:/usr/src/app/logs
    container_name: backend
    restart: unless-stopped
    networks:
      - fullstack
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - 3002:3002
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: frontend
    restart: unless-stopped
    networks:
      - fullstack
    depends_on:
      - backend

networks:
  fullstack:
    driver: bridge
